### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by Deborah-Digges**
Sorry, this was silly!
Does the readdir call need to be async?

### CODE REVIEW

**Comment by Deborah-Digges** [comment]
yea uh?:D

**Comment by kishore-narendran** [comment]
When it can’t spot the unmatched bracket line. It needs it.

**Comment by Deborah-Digges** [comment]
Ah. But it also does overwrite all other messages. OK let me fix that :)

**Comment by kishore-narendran** [comment]
Oh shit then just return the results where they are being assigned.

**Comment by Deborah-Digges** [comment]
@kishore-narendran I'm a little unsure of the logic. Could you do it, please?

**Comment by kishore-narendran** [comment]
Cool, I’ll do it. No worries! I've written a little messy code. My bad.

**Comment by Deborah-Digges** [comment]
Thanks :smile: No it's too pro man :D

**Comment by kishore-narendran** [comment]
I cleaned it up in a6059155eade9695678442014e4d4d666d1c94d6

**Pull request merged**
